(function (B) {

  var nodes = [
    {id: 01, name: "Proto-Indo-European", type: "family"},
    {id: 02, name: "Indo-Iranian", type: "family"},
    {id: 03, name: "Hellenic", type: "family"},
    {id: 04, name: "Celtic", type: "family"},
    {id: 05, name: "Italic", type: "family"},
    {id: 06, name: "Balto-Slavic", type: "family"},
    {id: 07, name: "Germanic", type: "family"},
    {id: 08, name: "Tocharian", type: "family"},
    {id: 09, name: "Tocharian A", type: "language"},
    {id: 10, name: "Tocharian B", type: "language"},
    {id: 11, name: "Indic", type: "family"},
    {id: 12, name: "Iranian", type: "family"},
    {id: 13, name: "Sanskrit", type: "language"},
    {id: 14, name: "Bengali", type: "language", direct: true},
    {id: 15, name: "Hindi", type: "language", direct: true},
    {id: 16, name: "Urdu", type: "language", direct: true},
    {id: 17, name: "Gujarati", type: "language", direct: true},
    {id: 18, name: "Avestan", type: "language"},
    {id: 19, name: "Old Persian", type: "language"},
    {id: 20, name: "Middle Persian", type: "language"},
    {id: 21, name: "Farsi", type: "language", direct: true},
    {id: 22, name: "Kurdish", type: "language", direct: true},
    {id: 97, name: "Mycenean Greek", type: "language"},
    {id: 96, name: "Attic Greek", type: "language"},
    {id: 23, name: "Koine", type: "language"},
    {id: 24, name: "Modern Greek", type: "language", direct: true},
    {id: 25, name: "Brythonic", type: "family"},
    {id: 26, name: "Goidelic", type: "family"},
    {id: 27, name: "Continental", type: "family"},
    {id: 28, name: "Irish", type: "language", direct: true},
    {id: 29, name: "Gaelic", type: "language", direct: true},
    {id: 30, name: "Welsh", type: "language", direct: true},
    {id: 31, name: "Cornish", type: "language"},
    {id: 32, name: "Breton", type: "language", direct: true},
    {id: 33, name: "Gaulish", type: "language"},
    {id: 34, name: "Oscan", type: "language"},
    {id: 35, name: "Latin", type: "language"},
    {id: 36, name: "Classical Latin", type: "language"},
    {id: 37, name: "Vulgar Latin", type: "language"},
    {id: 38, name: "Romance", type: "family"},
    {id: 39, name: "Sardinian", type: "language", direct: true},
    {id: 40, name: "Continental Romance", type: "family"},
    {id: 41, name: "Western Romance", type: "family"},
    {id: 42, name: "Eastern Romance", type: "family"},
    {id: 43, name: "Castilian", type: "language", direct: true},
    {id: 44, name: "Old French", type: "language"},
    {id: 45, name: "French", type: "language", direct: true},
    {id: 46, name: "Provencal", type: "language", direct: true},
    {id: 47, name: "Italian", type: "language", direct: true},
    {id: 48, name: "Sicilian", type: "language", direct: true},
    {id: 49, name: "Romanian", type: "language", direct: true},
    {id: 50, name: "Portuguese", type: "language", direct: true},
    {id: 51, name: "Baltic", type: "family"},
    {id: 52, name: "Prussian", type: "language"},
    {id: 53, name: "Lithuanian", type: "language", direct: true},
    {id: 54, name: "Latvian", type: "language", direct: true},
    {id: 55, name: "Slavic", type: "family"},
    {id: 56, name: "Southern-Slavic", type: "family"},
    {id: 57, name: "Slovenian", type: "language", direct: true},
    {id: 58, name: "Bulgarian", type: "language", direct: true},
    {id: 59, name: "Serbo-Croatian", type: "language", direct: true},
    {id: 60, name: "Western Slavic", type: "family"},
    {id: 61, name: "Polish", type: "language", direct: true},
    {id: 62, name: "Czech", type: "language", direct: true},
    {id: 63, name: "Slovak", type: "language", direct: true},
    {id: 64, name: "Sorbian", type: "language", direct: true},
    {id: 65, name: "Eastern Slavic", type: "family"},
    {id: 66, name: "Belorussian", type: "language", direct: true},
    {id: 67, name: "Russian", type: "language", direct: true},
    {id: 68, name: "Ukrainian", type: "language", direct: true},
    {id: 69, name: "North Germanic", type: "family"},
    {id: 70, name: "Old Norse", type: "language"},
    {id: 71, name: "Norwegian", type: "language", direct: true},
    {id: 72, name: "Icelandic", type: "language", direct: true},
    {id: 73, name: "Swedish", type: "language", direct: true},
    {id: 74, name: "Danish", type: "language", direct: true},
    {id: 75, name: "East Germanic", type: "family"},
    {id: 76, name: "Gothic", type: "language"},
    {id: 77, name: "West Germanic", type: "family"},
    {id: 78, name: "Old High German", type: "language"},
    {id: 79, name: "Middle High German", type: "language"},
    {id: 80, name: "German", type: "language", direct: true},
    {id: 81, name: "Yiddish", type: "language", direct: true},
    {id: 98, name: "Old Dutch", type: "language"},
    {id: 82, name: "Middle Dutch", type: "language"},
    {id: 83, name: "Flemish", type: "language", direct: true},
    {id: 84, name: "Dutch", type: "language", direct: true},
    {id: 85, name: "Afrikaans", type: "language", direct: true},
    {id: 86, name: "North Sea Germanic", type: "language"},
    {id: 87, name: "Old Saxon", type: "language"},
    {id: 88, name: "Middle Low German", type: "language"},
    {id: 89, name: "Low German", type: "language", direct: true},
    {id: 90, name: "Anglo-Frisian", type: "language"},
    {id: 91, name: "Frisian", type: "language", direct: true},
    {id: 92, name: "Old English / Anglo-Saxon", type: "language"},
    {id: 93, name: "Middle English", type: "language"},
    {id: 94, name: "English", type: "language", direct: true},
    {id: 95, name: "Scots", type: "language", direct: true},
    {id: 100, name: "Albanian", type: "family"},
    {id: 101, name: "Illyrian", type: "language"},
    {id: 102, name: "Albanian", type: "language", direct: true},
    {id: 103, name: "Gheg", type: "dialect", direct: true},
    {id: 104, name: "Tosk", type: "dialect", direct: true},

    {id: 200, name: "Arabic", type: "language", direct: true},

    {id: 1000, name: "Balkan", type: "sprachbund"}

  ]

  var edges = [
    {source: 02, target: 01, relationship: "descends from"},
    {source: 03, target: 01, relationship: "descends from"},
    {source: 04, target: 01, relationship: "descends from"},
    {source: 05, target: 01, relationship: "descends from"},
    {source: 06, target: 01, relationship: "descends from"},
    {source: 07, target: 01, relationship: "descends from"},
    {source: 08, target: 01, relationship: "descends from"},

    // Tocharian
    {source: 09, target: 08, relationship: "descends from"},
    {source: 10, target: 09, relationship: "descends from"},

    // Indo-Iranian
    {source: 11, target: 02, relationship: "descends from"},
    {source: 12, target: 02, relationship: "descends from"},
    {source: 13, target: 11, relationship: "descends from"},
    {source: 14, target: 13, relationship: "descends from"},
    {source: 15, target: 13, relationship: "descends from"},
    {source: 16, target: 13, relationship: "descends from"},
    {source: 17, target: 13, relationship: "descends from"},
    {source: 18, target: 12, relationship: "descends from"},
    {source: 19, target: 12, relationship: "descends from"},
    {source: 20, target: 19, relationship: "descends from"},
    {source: 21, target: 20, relationship: "descends from"},
    {source: 22, target: 20, relationship: "descends from"},

    // Hellenic
    {source: 97, target: 03, relationship: "descends from"},
    {source: 96, target: 97, relationship: "descends from"},
    {source: 23, target: 97, relationship: "descends from"},
    {source: 24, target: 23, relationship: "descends from"},

    // Celtic
    {source: 25, target: 04, relationship: "descends from"},
    {source: 26, target: 04, relationship: "descends from"},
    {source: 27, target: 04, relationship: "descends from"},
    {source: 28, target: 26, relationship: "descends from"},
    {source: 29, target: 26, relationship: "descends from"},
    {source: 30, target: 25, relationship: "descends from"},
    {source: 31, target: 25, relationship: "descends from"},
    {source: 32, target: 25, relationship: "descends from"},
    {source: 33, target: 27, relationship: "descends from"},

    // Italic
    {source: 34, target: 05, relationship: "descends from"},
    {source: 35, target: 05, relationship: "descends from"},
    {source: 36, target: 35, relationship: "descends from"},
    {source: 37, target: 35, relationship: "descends from"},
    {source: 38, target: 37, relationship: "descends from"},
    {source: 39, target: 38, relationship: "descends from"},
    {source: 40, target: 38, relationship: "descends from"},
    {source: 41, target: 40, relationship: "descends from"},
    {source: 42, target: 40, relationship: "descends from"},
    {source: 43, target: 41, relationship: "descends from"},
    {source: 44, target: 41, relationship: "descends from"},
    {source: 45, target: 44, relationship: "descends from"},
    {source: 46, target: 44, relationship: "descends from"},
    {source: 47, target: 42, relationship: "descends from"},
    {source: 48, target: 42, relationship: "descends from"},
    {source: 49, target: 42, relationship: "descends from"},
    {source: 50, target: 41, relationship: "descends from"},

    // Balto-Slavic
    {source: 51, target: 06, relationship: "descends from"},
    {source: 52, target: 51, relationship: "descends from"},
    {source: 53, target: 51, relationship: "descends from"},
    {source: 54, target: 51, relationship: "descends from"},
    {source: 55, target: 06, relationship: "descends from"},
    {source: 56, target: 55, relationship: "descends from"},
    {source: 57, target: 56, relationship: "descends from"},
    {source: 58, target: 56, relationship: "descends from"},
    {source: 59, target: 56, relationship: "descends from"},
    {source: 60, target: 55, relationship: "descends from"},
    {source: 61, target: 60, relationship: "descends from"},
    {source: 62, target: 60, relationship: "descends from"},
    {source: 63, target: 60, relationship: "descends from"},
    {source: 64, target: 60, relationship: "descends from"},
    {source: 65, target: 55, relationship: "descends from"},
    {source: 66, target: 65, relationship: "descends from"},
    {source: 67, target: 65, relationship: "descends from"},
    {source: 68, target: 65, relationship: "descends from"},

    // Germanic
    {source: 69, target: 07, relationship: "descends from"},
    {source: 70, target: 69, relationship: "descends from"},
    {source: 71, target: 70, relationship: "descends from"},
    {source: 72, target: 70, relationship: "descends from"},
    {source: 73, target: 69, relationship: "descends from"},
    {source: 74, target: 69, relationship: "descends from"},
    {source: 75, target: 07, relationship: "descends from"},
    {source: 76, target: 75, relationship: "descends from"},
    {source: 77, target: 07, relationship: "descends from"},
    {source: 78, target: 77, relationship: "descends from"},
    {source: 79, target: 78, relationship: "descends from"},
    {source: 80, target: 79, relationship: "descends from"},
    {source: 81, target: 79, relationship: "descends from"},
    {source: 98, target: 77, relationship: "descends from"},
    {source: 82, target: 98, relationship: "descends from"},
    {source: 83, target: 82, relationship: "descends from"},
    {source: 84, target: 82, relationship: "descends from"},
    {source: 85, target: 82, relationship: "descends from"},
    {source: 86, target: 07, relationship: "descends from"},
    {source: 87, target: 86, relationship: "descends from"},
    {source: 88, target: 87, relationship: "descends from"},
    {source: 89, target: 88, relationship: "descends from"},
    {source: 90, target: 86, relationship: "descends from"},
    {source: 90, target: 86, relationship: "descends from"},
    {source: 91, target: 90, relationship: "descends from"},
    {source: 92, target: 90, relationship: "descends from"},
    {source: 93, target: 92, relationship: "descends from"},
    {source: 94, target: 93, relationship: "descends from"},
    {source: 95, target: 93, relationship: "descends from"},

    // Illyrian
    {source: 100, target: 01, relationship: "descends from"},
    {source: 101, target: 100, relationship: "descends from"},
    {source: 102, target: 101, relationship: "descends from"},
    {source: 103, target: 102, relationship: "descends from"},
    {source: 104, target: 102, relationship: "descends from"},

    // Influences - for complexities sake.
    {source: 94, target: 95, relationship: "influences"},
    {source: 96, target: 36, relationship: "influences"},
    {source: 96, target: 94, relationship: "influences"},
    {source: 96, target: 80, relationship: "influences"},
    {source: 96, target: 45, relationship: "influences"},
    {source: 44, target: 93, relationship: "influences"},
    {source: 94, target: 80, relationship: "influences"},
    {source: 94, target: 67, relationship: "influences"},
    {source: 94, target: 30, relationship: "influences"},
    {source: 94, target: 28, relationship: "influences"},
    {source: 94, target: 29, relationship: "influences"},
    {source: 94, target: 73, relationship: "influences"},
    {source: 94, target: 74, relationship: "influences"},
    {source: 67, target: 62, relationship: "influences"},
    {source: 67, target: 61, relationship: "influences"},
    {source: 67, target: 63, relationship: "influences"},
    {source: 80, target: 64, relationship: "influences"},
    {source: 94, target: 62, relationship: "influences"},
    {source: 80, target: 62, relationship: "influences"},
    {source: 45, target: 32, relationship: "influences"},
    {source: 36, target: 94, relationship: "influences"},
    {source: 36, target: 80, relationship: "influences"},
    {source: 36, target: 45, relationship: "influences"},
    {source: 36, target: 43, relationship: "influences"},
    {source: 37, target: 25, relationship: "influences"},
    {source: 200, target: 43, relationship: "influences"},
    {source: 200, target: 16, relationship: "influences"},
    {source: 94, target: 15, relationship: "influences"},
    {source: 23, target: 101, relationship: "influences"},

    // Areal influences.
    {source: 24, target: 1000, relationship: "belongs to"},
    {source: 58, target: 1000, relationship: "belongs to"},
    {source: 59, target: 1000, relationship: "belongs to"},
    {source: 49, target: 1000, relationship: "belongs to"},
    {source: 49, target: 1000, relationship: "belongs to"},
    {source: 102, target: 1000, relationship: "belongs to"}


  ];

  var viewer = new B.DAGViewer({
    target: 'dag-viewer',
    edgeLabels: ['relationship'],
    edgeProps: ['source', 'target'],
    termTemplate: '<li><a><%- name %></a></li>',
    termKey: function (t) { return t.id },
    getEnds: function (e) { return [e.get('source'), e.get('target')] },
    edgeKey: function (e) { return String(e.source) + e.relationship + String(e.target) },
    getNodeClass: function (node) { return node.get('type'); }
  });
  viewer.setGraph({nodes: nodes, edges: edges});

})(window.Biojs);
